template: Hello, %s!
defaultName: Stranger

server:
  rootPath: /api/*
  applicationConnectors:
    - type: http
      port: 8082
  #    - type: https
  #      port: 8443
  #      keyStorePath: test.keystore
  #      keyStorePassword: test
  adminConnectors:
    - type: http
      port: 8081
#    - type: https
#      port: 8444
#      keyStorePath: test.keystore
#      keyStorePassword: test

# Database settings.
database:
  # the name of your JDBC driver
  driverClass: com.mysql.cj.jdbc.Driver

  # the username
  user: root

  # the password
  password: password

  # the JDBC URL
  url: jdbc:mysql://127.0.0.1:3307/wizarddb?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
#      layout:
#        type: json
